### ISSUE TITLE
Review Medium TOS

### ISSUE THREAD

**Issue by JasonvanBrackel** [project-zot/docs-zot#4]

**Comment by JasonvanBrackel** [comment]
Terms of Service
https://policy.medium.com/medium-terms-of-service-9db0094a1e0f

Privacy Policy
https://policy.medium.com/medium-privacy-policy-f03bf92035c9

Rules
https://policy.medium.com/medium-rules-30e5502c4eb4

Username Policy
https://policy.medium.com/medium-username-policy-7054a77fb04f

Membership Terms of Service
https://policy.medium.com/paid-terms-of-service-cc7f8e165178

Trademark Policy
https://policy.medium.com/mediums-trademark-policy-e3bb53df59a7

Guidelines for Law Enforcement
https://policy.medium.com/mediums-guidelines-for-law-enforcement-e289ed6304b8

Items of note

**From the TOS**
> You retain your rights to any content you submit, post or display on or through the Services.
> 
> Unless otherwise agreed in writing, by submitting, posting, or displaying content on or through the Services, you grant Medium a nonexclusive, royalty-free, worldwide, fully paid, and sublicensable license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, publicly perform and display your content and any name, username or likeness provided in connection with your content in all media formats and distribution methods now known or later developed on the Services.
> 
> Medium needs this license because you own your content and Medium therefore can’t display it across its various surfaces (i.e., mobile, web) without your permission.
> 
> This type of license also is needed to distribute your content across our Services. For example, you post a story on Medium. It is reproduced as versions on both our website and app, and distributed to multiple places within Medium, such as the homepage or reading lists. A modification might be that we show a snippet of your work (and not the full post) in a preview, with attribution to you. A derivative work might be a list of top authors or quotes on Medium that uses portions of your content, again with full attribution. This license applies to our Services only, and does not grant us any permissions outside of our Services.
> 
> So long as you comply with these Terms, Medium gives you a limited, personal, non-exclusive, and non-assignable license to access and use our Services.

---------

> 
> Indemnification
> 
> To the fullest extent permitted by applicable law, you will indemnify, defend and hold harmless Medium, and our officers, directors, agents, partners and employees (individually and collectively, the “Medium Parties”) from and against any losses, liabilities, claims, demands, damages, expenses or costs (“Claims”) arising out of or related to your violation, misappropriation or infringement of any rights of another (including intellectual property rights or privacy rights) or your violation of the law. You agree to promptly notify Medium Parties of any third-party Claims, cooperate with Medium Parties in defending such Claims and pay all fees, costs and expenses associated with defending such Claims (including attorneys’ fees). You also agree that the Medium Parties will have control of the defense or settlement, at Medium’s sole option, of any third-party Claims.


----------


 From Member TOS
 
 

> License. 
> Your use of the Member Services must be only for personal, non-commercial use. You agree not to use any Member Service, in whole or in part in connection with any public presentation even if no fee is charged (except where such use would not constitute a copyright infringement). You are receiving a non-exclusive license to access the Member Services and all rights, title and interest in the Member Services (including any content offered through the Member Services) not expressly granted to you in these Terms are reserved by Medium and its licensors. If Medium reasonably determines that you violated any part of the Membership Terms of Service, your rights under this Section will immediately terminate and Medium may terminate your access to the Member Services and/or your Medium account without notice and without refund to you.

**Comment by JasonvanBrackel** [comment]
@rchamarthy I don't see anything major here.  Would anything in these paragraphs be any issue to us?

**Comment by rchamarthy** [comment]
No I do not see an issue. As per plan lets write the content into our docs-zot repo and then either manually or automatically push the content to medium. This repo will decide the master content and I suggest we just use creative commons for the blog/doc license. As open as possible.
