### ISSUE TITLE
Document steps for the user to build/push container images having all fields consumed by zui and shown in the image and repo cards

### ISSUE THREAD

**Issue by andaaron** [project-zot/docs-zot#67]
Ideally as part of the docs-zot repo.

Currently our queries return ImageSummary objects containing information originating in the image config object (see: https://github.com/opencontainers/image-spec/blob/main/config.md).
More specifically we use pre-defined labels from https://github.com/opencontainers/image-spec/blob/main/annotations.md#rules.

The labels we used at the moment in zot are: https://github.com/project-zot/zot/blob/8ffb053cec01bd7541ef40679f5ad24d44070fce/pkg/extensions/search/common/common.go#L106

1. We are interested to know what steps a user needs to make in order to build images containing those labels. What skopeo/docker/podman settings does he need to use in order to obtain images with those labels?
2. What steps does the user need to take at build time in order to set Annotations in the manifest https://github.com/opencontainers/image-spec/blob/main/manifest.md
3. Are we using these fields correctly? What's the difference between the annotations/labels mentioned above? Do we need to update the linter rules to verify Labels in the image config instead of annotations in the manifest? 
4. How to set image Author per https://github.com/opencontainers/image-spec/blob/main/config.md?
5. Which of the tools generate/add labels with the `org.label-schema.*` keys and which with the `org.opencontainers.image.*` keys?

**Comment by andaaron** [comment]
https://github.com/project-stacker/stacker/blob/master/doc/stacker_yaml.md#environment-labels-working_dir-volumes-cmd-entrypoint-user may be worth while investigating.

**Comment by nicoldr** [comment]
**Annotations:**

Components like Image Manifests and Descriptors feature an optional annotations property that contains arbitrary data, intended but not limited to image index, image manifest, artifact, and descriptor authors. The format is defined at https://github.com/opencontainers/image-spec/blob/main/annotations.md#rules
Label Schema defined conventional labels for container images that are now superceded by annotations with keys starting org.opencontainers.image. Users are now encouraged to use the org.opencontainers.image keys, but some tools MAY still support using the org.label-schema prefix. For some labels, there is a compatible adnotation in using the org.label-schema prefix.
More information can be found at https://github.com/opencontainers/image-spec/blob/main/annotations.md#back-compatibility-with-label-schema
vendor		- 	vendor (compatible)
description	-	description (compatible)
licenses	-	No equivalent in Label Schema

**Config Labels**:
Each image has an associated JSON structure that describes some basic information about the image such as date created, author, as well as execution/runtime configuration like its entry point, default arguments, networking, and volumes. The "LABELS" OPTIONAL field contains arbitrary metadata for the container.
"Labels": {
            "com.example.project.git.url": "https://example.com/project.git",
            "com.example.project.git.commit": "45a939b2999782a3f005621a8d0f29aa387e1d6b"
        }
Both Annotations and Labels MUST use the annotation rules (https://github.com/opencontainers/image-spec/blob/main/config.md#:~:text=use%20the%20annotation%20rules.)



*** How to build images that contain these data?**

**_Podman build:_**

--annotation=annotation¶
Add an image annotation (e.g. annotation=value) to the image metadata. Can be used multiple times.
Note: This information is not present in Docker image formats, so it is discarded when writing images in Docker formats.
Source https://docs.podman.io/en/latest/markdown/podman-build.1.html#annotation-annotation
	Example: podman build . --format oci --annotation vendor="CentOS" --annotation licenses="GPLv2"
Where "vendor" and "licenses" are two added annotations that are displayed after building in the image manifest.

_**Docker:**_

Adding custom image metadata with Docker can be done in two ways. One way is to add a label to a Docker image by adding the LABEL instruction to a Dockerfile, while another way is by adding them to the docker build command using the --label flag.

Add custom metadata to the Docker image by adding the LABEL instruction to a Dockerfile: 
LABEL <key>=<value>
Example:
# Label docker image
LABEL vendor="CentOS"
LABEL licenses="GPLv2"
Note: Prior to Docker 1.10, it was recommended to combine all labels into a single LABEL instruction, to prevent extra layers from being created. This is no longer necessary, but combining labels is still supported (source and examples: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#label).

Label Docker images by using the "--label" flag with the docker build command:
	docker build --label vendor="CentOS" --label licenses="GPLv2".
To list labels use the docker inspect command.

**Comment by andaaron** [comment]
@nicoldr let's also investigate adding annotations using the oras toolchain, if I understood correctly you could add them as separate artifacts.

**Comment by nicoldr** [comment]
Annotations are supported by ORAS and they can be made to the manifest, the config, and individual files(i.e. layers) by using "--manifest-annotations <annotations_file>" option". The annotations file is a JSON that can have to special filename or entires:
- $config is used for the annotation of the manifest config
- $manifest is reserved for the annotation of the manifest itself
Annotation file example, annotations.json:
{
  "$config": {
    "hello": "world"
  },
  "$manifest": {
    "foo": "bar"
  },
  "cake.txt": {
    "fun": "more cream"
  }
}

The command to run ORAS and add the desired annotations is:
oras push --manifest-annotations annotations.json localhost:5000/club:party cake.txt juice.txt
Note: After this, the manifest will be replaced and the old layers and config are not kept as a reference.

This link may also be useful: https://oras.land/cli/6_reference_types/
Example:
	oras push $REGISTRY/$REPO \
	--artifact-type 'signature/example' \
	--subject $IMAGE \
	./annotations.json:application/json

Where the annotations file is pushed to the registry, as a reference to the container image.
